declare const classNames: {
  readonly BaseQueryModule: "BaseQueryModule";
  readonly PlaceholderQueryModule: "PlaceholderQueryModule";
  readonly PlaceholderQueryModuleTrigger: "PlaceholderQueryModuleTrigger";
  readonly TypeDialog: "TypeDialog";
  readonly TypeDialogSplit: "TypeDialogSplit";
  readonly TypeDialog__Left: "TypeDialog__Left";
  readonly VerticalRuler: "VerticalRuler";
  readonly TypeDialog__Right: "TypeDialog__Right";
  readonly TypeDialog__Section: "TypeDialog__Section";
  readonly TypeDialogActionButtons: "TypeDialogActionButtons";
  readonly TypeDialogGridItemImage: "TypeDialogGridItemImage";
  readonly QueryModuleIcon: "QueryModuleIcon";
  readonly QueryModuleTitle: "QueryModuleTitle";
  readonly QueryModuleIconWithText: "QueryModuleIconWithText";
  readonly SpacedChildren: "SpacedChildren";
  readonly SpacedSmall: "SpacedSmall";
  readonly ControlWithLabel: "ControlWithLabel";
  readonly ControlWithLabel__Label: "ControlWithLabel__Label";
  readonly IconBase: "IconBase";
  readonly IconLarge: "IconLarge";
  readonly IconToggled: "IconToggled";
  readonly IconUnToggled: "IconUnToggled";
  readonly FileTreeWrapper: "FileTreeWrapper";
  readonly CloseIcon: "CloseIcon";
  readonly ContainsErrors: "ContainsErrors";
};
export = classNames;
