name: "setup-rust"
description: "Setup Rust"

runs:
  using: "composite"
  steps:
    - uses: moonrepo/setup-rust@v1
      with:
        channel: "1.73.0"
        components: clippy
        targets: "wasm32-wasi"
