yarnPath: .yarn/releases/yarn-3.5.0.cjs
nodeLinker: node-modules

packageExtensions:
  "@storybook/manager-api@*":
    peerDependencies:
      "react": ">=18.0.0"
      "react-dom": ">=18.0.0"
  "@storybook/addon-controls@*":
    peerDependencies:
      "react": ">=18.0.0"
      "react-dom": ">=18.0.0"
  react-resizable@*:
    peerDependencies:
      "react-dom": ">=18.0.0"
