declare const classNames: {
  readonly Canvas: "Canvas";
  readonly CanvasPaddingWrapper: "CanvasPaddingWrapper";
  readonly CanvasWrapper: "CanvasWrapper";
  readonly Stage: "Stage";
  readonly StageRow: "StageRow";
  readonly Toolbar: "Toolbar";
  readonly Separator: "Separator";
  readonly ControlWithLabel: "ControlWithLabel";
  readonly ControlWithLabel__Label: "ControlWithLabel__Label";
  readonly ToolbarButton: "ToolbarButton";
  readonly SidePanel: "SidePanel";
  readonly Vr: "Vr";
  readonly SidePanel__Bottom: "SidePanel__Bottom";
  readonly SidePanel__Link: "SidePanel__Link";
  readonly MinimapContainer: "MinimapContainer";
  readonly Minimap: "Minimap";
  readonly MinimapPreview: "MinimapPreview";
  readonly MinimapPreviewHover: "MinimapPreviewHover";
  readonly MinimapPreviewDragging: "MinimapPreviewDragging";
  readonly EmptySelectionOverlay: "EmptySelectionOverlay";
  readonly LegendContainer: "LegendContainer";
  readonly DebugOverlay: "DebugOverlay";
  readonly ErrorOverlay: "ErrorOverlay";
  readonly ErrorOverlayVisible: "ErrorOverlayVisible";
  readonly ErrorTable: "ErrorTable";
};
export = classNames;
