declare const classNames: {
  readonly CardTitle: "CardTitle";
  readonly Card: "Card";
  readonly CardHead: "CardHead";
  readonly RightAlignedGroup: "RightAlignedGroup";
  readonly Panel: "Panel";
  readonly Section: "Section";
  readonly SectionHead: "SectionHead";
  readonly SectionBody: "SectionBody";
  readonly Block: "Block";
  readonly sectionBody: "sectionBody";
  readonly block: "block";
  readonly InlineRow: "InlineRow";
  readonly FullWidth: "FullWidth";
  readonly ToolbarIcon: "ToolbarIcon";
  readonly FlexGrow: "FlexGrow";
  readonly Pointer: "Pointer";
  readonly PopoverUnderlay: "PopoverUnderlay";
};
export = classNames;
