[package]
name = "explorer-backend-libgit2"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]



[dependencies]
# The `wasm-bindgen` crate provides the bare minimum functionality needed
# to interact with JavaScript.
wasm-bindgen = "0.2.84"

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. However, it is slower than the default
# allocator, so it's not enabled by default.
wee_alloc = { version = "0.4.5", optional = true }


[dependencies.web-sys]
version = "0.3.61"
features = ["console"]


[target."cfg(debug_assertions)".dependencies]
console_error_panic_hook = "0.1.7"

# These crates are used for running unit tests.
[dev-dependencies]
wasm-bindgen-test = "0.3.34"
futures = "0.3.27"
js-sys = "0.3.61"
wasm-bindgen-futures = "0.4.34"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
wasm-pack = "0.10.3"
