[package]
name = "explorer-backend-libgit2"
version = "0.0.0"
edition = "2021"

[dependencies]
asyncify_exports = { path = "../asyncify_exports" }
structopt = "0.3"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_with = "3.0.0"
#git2 = { git = "https://github.com/gizual/git2-rs", default-features = false, branch = "wasm32-wasi-support", features = [
#  "vendored-zlib"
#] }

git2 = { path = "../../../git2-rs", default-features = false,  features = [
  "vendored-zlib"
] }
[dev-dependencies]
