[package]
name = "explorer"
version = "0.0.0"
edition = "2021"

[dependencies]
specta = { workspace = true }
asyncify_exports = { workspace = true }
structopt = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_with = { workspace = true }
md5 = "0.6.0"
lazy_static = "1.4.0"
regex = { workspace = true }
git2 = {  workspace = true }


[target.'cfg(not(target_os = "wasm"))'.dependencies]
petgraph = "0.6.3"

[dev-dependencies]
