[package]
name = "explorer"
version = "0.0.0"
edition = "2021"

[[bin]]
name = "bindings"
path = "src/main-bindings.rs"

[dependencies]
structopt = { workspace = true }
specta = { workspace = true, features = ["export", "typescript"], optional = true }
serde_json = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_with = { workspace = true }
md5 = "0.6.0"
lazy_static = "1.4.0"
regex = { workspace = true }
git2 = { workspace = true }
base64 = "0.22.1"

[target.'cfg(not(target_os = "wasm"))'.dependencies]
petgraph = "0.6.3"

[features]
default = ["bindings"]
bindings = ["dep:specta"]
