// This file has been generated by Specta. DO NOT EDIT.

export type Author = { id: string; name: string; email: string; gravatarHash: string }

export type AuthorInfo = { id: string; name: string; email: string }

export type Blame = { fileName: string; commits: { [key in string]: CommitInfo }; lines: BlameLine[] }

export type BlameLine = { lineNo: number; commitId: string; content: string }

export type BlameParams = { branch: string; path: string; preview?: boolean | null; range: CommitIds }

export type BranchInfo = { id: string; name: string; last_commit_id: string }

export type Commit = { oid: string; aid: string; message: string; files: string[]; timestamp: string }

export type CommitIds = { start_id: string; end_id: string }

export type CommitInfo = { commitId: string; authorId: string; timestamp: string }

export type CommitTree = { graph: HistoryGraph; dot: string }

export type CommitsForBranch = { start_commit: string; end_commit: string }

export type FileTreeNode = { path: string[]; kind?: any | null; loading?: boolean | null }

export type GetCommitIdsForRefsParams = { start_ref: string; end_ref: string }

export type GetCommitIdsForTimeRangeParams = { branch: string; start_seconds: number; end_seconds: number }

export type GetCommitsForBranchParams = { branch: string }

export type GetFileContentParams = { branch: string; path: string; range: CommitIds }

export type GetFileTreeParams = { branch: string; range?: CommitIds | null }

export type GitGraphCommitInfo = { oid: string; aid: string; timestamp: string; message: string; is_merge: boolean; parents: (string | null)[]; children: string[] }

export type HistoryGraph = { commit_indices: { [key in string]: number }; commits: GitGraphCommitInfo[]; branches: BranchInfo[] }

export type Infallible = never

export type InitialDataResult = { currentBranch: string; commit: Commit }

export type NoParams = Record<string, never>

export type OpenRepositoryParams = { path: string }

export type OpenRepositoryResult = { success: boolean }

export type StreamAuthorsParams = Record<string, never>

export type StreamCommitsParams = Record<string, never>

