declare const classNames: {
  readonly Container: "Container";
  readonly Clickable: "Clickable";
  readonly AdvancedSearchIconTrigger: "AdvancedSearchIconTrigger";
  readonly AdvancedSearchIconButton: "AdvancedSearchIconButton";
  readonly AdvancedSearchIcon: "AdvancedSearchIcon";
  readonly Content: "Content";
  readonly SearchModule: "SearchModule";
  readonly SearchModuleIcon: "SearchModuleIcon";
  readonly SearchModuleTitle: "SearchModuleTitle";
  readonly SearchModuleIconWithText: "SearchModuleIconWithText";
  readonly SpacedChildren: "SpacedChildren";
  readonly CloseIcon: "CloseIcon";
  readonly IconBase: "IconBase";
  readonly IconToggled: "IconToggled";
  readonly IconUnToggled: "IconUnToggled";
  readonly FileTreeWrapper: "FileTreeWrapper";
  readonly ControlWithLabel: "ControlWithLabel";
  readonly ControlWithLabel__Label: "ControlWithLabel__Label";
  readonly SpacedSmall: "SpacedSmall";
};
export = classNames;
