declare const classNames: {
  readonly SearchModule: "SearchModule";
  readonly SearchModulePlaceholder: "SearchModulePlaceholder";
  readonly SearchModulePlaceholderTrigger: "SearchModulePlaceholderTrigger";
  readonly TypeSteps: "TypeSteps";
  readonly TypeDialog: "TypeDialog";
  readonly TypeDialogGrid: "TypeDialogGrid";
  readonly TypeDialogGridItemTile: "TypeDialogGridItemTile";
  readonly TypeDialogGridItem: "TypeDialogGridItem";
  readonly TypeDialogGridItemImage: "TypeDialogGridItemImage";
  readonly TypeDialogGridItemContent: "TypeDialogGridItemContent";
  readonly TypeDialogGridItemTitle: "TypeDialogGridItemTitle";
  readonly TypeDialogGridItemDescription: "TypeDialogGridItemDescription";
  readonly SearchModuleIcon: "SearchModuleIcon";
  readonly SearchModuleTitle: "SearchModuleTitle";
  readonly SearchModuleIconWithText: "SearchModuleIconWithText";
  readonly SpacedChildren: "SpacedChildren";
  readonly SpacedSmall: "SpacedSmall";
  readonly ControlWithLabel: "ControlWithLabel";
  readonly ControlWithLabel__Label: "ControlWithLabel__Label";
  readonly IconBase: "IconBase";
  readonly IconToggled: "IconToggled";
  readonly IconUnToggled: "IconUnToggled";
  readonly FileTreeWrapper: "FileTreeWrapper";
  readonly CloseIcon: "CloseIcon";
};
export = classNames;
