declare const classNames: {
  readonly Timeline: "Timeline";
  readonly TimelineComponent: "TimelineComponent";
  readonly TimelineContainer: "TimelineContainer";
  readonly TimelineSvgWrapper: "TimelineSvgWrapper";
  readonly TimelineInfoColumn: "TimelineInfoColumn";
  readonly CurrentBranchInfoContainer: "CurrentBranchInfoContainer";
  readonly InteractionLayer: "InteractionLayer";
  readonly Header: "Header";
  readonly TimelineHeader: "TimelineHeader";
  readonly RectContainer: "RectContainer";
  readonly Tooltip: "Tooltip";
  readonly SelectionBox: "SelectionBox";
  readonly SelectionBoxLine: "SelectionBoxLine";
  readonly RulerAnnotationLeft: "RulerAnnotationLeft";
  readonly RulerAnnotationRight: "RulerAnnotationRight";
  readonly BranchName: "BranchName";
  readonly CommitCircle: "CommitCircle";
  readonly CommitCircleHover: "CommitCircleHover";
  readonly CommitCircleHighlight: "CommitCircleHighlight";
  readonly Svg: "Svg";
  readonly timelineOverlay: "timelineOverlay";
  readonly timelineOverlayContent: "timelineOverlayContent";
};
export = classNames;
