name: cleanup-after-pr

on:
  pull_request:
    types: [closed]

permissions:
  contents: read
  id-token: write
  packages: write

env:
  REGISTRY: ghcr.io

jobs:
  remove-images:
    strategy:
      matrix:
        IMAGE_NAME: ["${{ github.repository }}-web", "${{ github.repository }}-landing-page"]
    runs-on: ubuntu-22.04
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete image
        uses: bots-house/ghcr-delete-image-action@v1.1.0
        with:
          owner: ${{ github.repository_owner }}
          name: ${{ env.IMAGE_NAME }}
          tag: pr-${{github.event.pull_request.number}}
          token: ${{ secrets.GITHUB_TOKEN }}
