name: e2e-update

on:
  issue_comment:
    types: [created, edited]

permissions:
  contents: read

jobs:
  build:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/ci update-snapshots') }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Checkout the branch from the PR that triggered the job
        run: |
          # PR branch remote must be checked out using https URL
          git config --global hub.protocol https
          git config --global --add safe.directory '*'

          gh pr checkout ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      - run: yarn --immutable

      - name: Setup Rust
        uses: ./.github/actions/setup-rust

      - name: Build the app
        run: yarn build

      - name: Store the build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: |
            apps/gizual-app/dist/
            apps/gizual-api/dist/
          retention-days: 1

  update-snapshots:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/ci update-snapshots') }}
    needs: build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/steschi/playwright:v1.42.1-jammy
    permissions:
      contents: write # This is required to push the changes to the PR branch
      pull-requests: write # This is required to react to the triggering comment
    steps:
      # github-runner is messing up the HOME env variable
      # as can be seen at https://github.com/actions/runner/issues/863
      # this is a workaround to fix it
      - run: echo "HOME=/root" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: React to the triggering comment
        run: |
          gh api repos/${{ github.repository }}/issues/comments/${{ github.event.comment.id }}/reactions --raw-field 'content=+1'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout the branch from the PR that triggered the job
        run: |
          # PR branch remote must be checked out using https URL
          git config --global hub.protocol https
          git config --global --add safe.directory '*'

          gh pr checkout ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Retrieve the build artifacts
        uses: actions/download-artifact@v4
        with:
          name: web-dist
          path: apps/

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      - name: Setup Api deps
        run: cd apps/gizual-api/dist && npm install

      - name: Install e2e deps
        run: |
          cd e2e
          yarn install --immutable

      - name: Update snapshots
        run: |
          cd e2e
          yarn e2e:update

      - name: Commit and push the changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci: update snapshots"
          file_pattern: "e2e/**/*.png"
          disable_globbing: true
