name: e2e-update

on:
  issue_comment:
    types: [created, edited]

permissions:
  contents: read

jobs:
  update-snapshots:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/ci update-snapshots') }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/steschi/playwright:v1.42.1-jammy
    permissions:
      contents: write # This is required to push the changes to the PR branch
      pull-requests: write # This is required to react to the triggering comment
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: React to the triggering comment
        run: |
          gh api repos/${{ github.repository }}/issues/comments/${{ github.event.comment.id }}/reactions --raw-field 'content=+1'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout the branch from the PR that triggered the job
        run: |
          # PR branch remote must be checked out using https URL
          git config --global hub.protocol https

          gh pr checkout ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install the packages
        run: |
          cd e2e
          yarn install --immutable

      - name: Build api and app # We should probaby reuse the build artifacts eventually
        run: yarn build

      - name: Update snapshots
        run: |
          cd e2e
          yarn e2e:update

      - name: Commit and push the changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci: update snapshots"
          file_pattern: "e2e/**/*.png"
          disable_globbing: true
