name: web
on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
    tags:
      - "v*"

permissions:
  contents: read
  id-token: write
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      - run: yarn --immutable

      - name: Setup Rust
        uses: ./.github/actions/setup-rust

      - name: Build the app
        run: yarn build

      - name: Store the build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: |
            apps/gizual-app/dist/
            apps/gizual-api/dist/
          retention-days: 1

  e2e:
    needs: build
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/steschi/playwright:v1.42.1-jammy
    steps:
      # github-runner is messing up the HOME env variable
      # as can be seen at https://github.com/actions/runner/issues/863
      # this is a workaround to fix it
      - run: echo "HOME=/root" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      - name: Retrieve the build artifacts
        uses: actions/download-artifact@v4
        with:
          name: web-dist
          # If multiple paths are provided as input, the least common ancestor
          # of all the search paths will be used as the root directory of the artifact.
          # https://github.com/actions/upload-artifact?tab=readme-ov-file#upload-using-multiple-paths-and-exclusions
          path: apps/

      - name: Setup Api deps
        run: cd apps/gizual-api/dist && npm install

      - name: Setup E2E tests
        run: cd e2e && yarn --immutable

      - name: Run E2E tests
        run: cd e2e && yarn e2e

      - name: Store the e2e artifacts
        uses: actions/upload-artifact@v4
        with:
          name: e2e-dist
          path: e2e/dist/
          retention-days: 1

  build-image:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Retrieve the build artifacts
        uses: actions/download-artifact@v4
        with:
          name: web-dist
          path: apps/

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag
            type=semver,event=tag,pattern={{major}}
            type=ref,event=pr
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile.web
          context: .
          push: ${{ startsWith(github.ref, 'refs/tags/') }} # Only push the image if the event was a tag
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build-image
    runs-on: ubuntu-22.04
    steps:
      - name: Call Webhook
        run: |
          curl --request GET '${{ secrets.COOLIFY_WEBHOOK_WEB }}' --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'
